version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: react-app
    restart: unless-stopped
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: flask-app
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      FLASK_ENV: production