version: '2.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      FLASK_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: react-app
    restart: unless-stopped
    ports:
      - "80:80"

